language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - docker build -t diadus/docker-react -f Dockerfile.dev .

script:
  - docker run diadus/docker-react npm run test -- --coverage